using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
#endif

// -----------------------------
// README UPDATER
// Snapshot alindiginda otomatik cagirilir
// Repo root README.md'yi gunceller
// -----------------------------

public static class ProjectStateReadmeUpdater
{
    private const string AutoBlockStart = "<!-- AUTOGENERATED README BLOCK - DO NOT EDIT BELOW -->";
    private const string AutoBlockEnd   = "<!-- END AUTOGENERATED README BLOCK -->";

#if UNITY_EDITOR

    public static void UpdateReadme(FullSnapshot snapshot)
    {
        string readmePath = GetReadmePath();

        string existing = File.Exists(readmePath)
            ? File.ReadAllText(readmePath, Encoding.UTF8)
            : BuildDefaultReadmeHeader();

        string manualPart = StripAutoBlock(existing);
        string autoBlock  = BuildAutoBlock(snapshot);
        string final      = manualPart.TrimEnd() + "\n\n" + autoBlock + "\n";

        File.WriteAllText(readmePath, final, Encoding.UTF8);
    }

    // -----------------------------
    // AUTO BLOCK
    // -----------------------------

    private static string BuildAutoBlock(FullSnapshot snapshot)
    {
        var sb = new StringBuilder();

        sb.AppendLine(AutoBlockStart);
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine($"*Auto-updated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}*");
        sb.AppendLine();

        // --- Project Status ---
        sb.AppendLine("## Project Status");
        sb.AppendLine();

        if (snapshot != null)
        {
            sb.AppendLine("| Field | Value |");
            sb.AppendLine("|-------|-------|");
            sb.AppendLine($"| Scene | `{snapshot.meta.activeSceneName}` |");
            sb.AppendLine($"| Unity | `{snapshot.meta.unityVersion}` |");
            sb.AppendLine($"| Last Snapshot | `{snapshot.meta.exportedAtLocalTime}` |");
            sb.AppendLine($"| Commit | `{snapshot.meta.headCommitShort}` — {snapshot.meta.headCommitMessage} |");
            sb.AppendLine($"| Objects in Scene | {snapshot.meta.totalGameObjectCount} |");
        }
        else
        {
            string commitShort   = ProjectStateGit.SafeGit("rev-parse --short HEAD");
            string commitMessage = ProjectStateGit.SafeGit("log -1 --pretty=%s");
            sb.AppendLine("| Field | Value |");
            sb.AppendLine("|-------|-------|");
            sb.AppendLine($"| Unity | `{Application.unityVersion}` |");
            sb.AppendLine($"| Commit | `{commitShort}` — {commitMessage} |");
            sb.AppendLine($"| Updated | `{DateTime.Now:yyyy-MM-dd HH:mm:ss}` |");
        }

        // --- Scripts ---
        sb.AppendLine();
        sb.AppendLine("## Scripts");
        sb.AppendLine();

        if (snapshot?.code?.csFiles != null)
        {
            var groups = new Dictionary<string, List<string>>();

            foreach (var f in snapshot.code.csFiles)
            {
                if (f?.relativePath == null) continue;
                if (f.relativePath.Contains("TutorialInfo")) continue;
                if (f.relativePath.Contains("ProjectState"))  continue;

                string shortPath = f.relativePath.Replace('\\', '/');
                string folder    = GetFolder(shortPath);

                if (!groups.ContainsKey(folder))
                    groups[folder] = new List<string>();
                groups[folder].Add(Path.GetFileName(shortPath));
            }

            foreach (var kvp in groups)
            {
                sb.AppendLine($"**{kvp.Key}**");
                foreach (var file in kvp.Value)
                    sb.AppendLine($"- `{file}`");
                sb.AppendLine();
            }
        }
        else
        {
            sb.AppendLine("- (Snapshot verisi yok)");
        }

        // --- Todo Progress ---
        sb.AppendLine("## Progress");
        sb.AppendLine();
        try
        {
            var all  = ProjectStateTodoSync.ReadAll();
            int open = 0, done = 0;
            foreach (var item in all)
                if (item.done) done++; else open++;

            int total   = open + done;
            int percent = total > 0 ? (done * 100 / total) : 0;
            int barLen  = 20;
            int filled  = (int)(barLen * percent / 100f);
            string bar  = "[" + new string('█', filled) + new string('░', barLen - filled) + "]";

            sb.AppendLine($"{bar} {percent}% ({done}/{total} tasks done)");
            sb.AppendLine();

            // Son 5 tamamlanan
            var doneItems = new List<ProjectStateTodoSync.TodoItem>();
            foreach (var item in all)
                if (item.done) doneItems.Add(item);

            if (doneItems.Count > 0)
            {
                sb.AppendLine("**Recently completed:**");
                int start = Math.Max(0, doneItems.Count - 5);
                for (int i = doneItems.Count - 1; i >= start; i--)
                    sb.AppendLine($"- ✅ {doneItems[i].text}");
                sb.AppendLine();
            }

            // Siradaki 5 open
            var openItems = new List<ProjectStateTodoSync.TodoItem>();
            foreach (var item in all)
                if (!item.done) openItems.Add(item);

            if (openItems.Count > 0)
            {
                sb.AppendLine("**Up next:**");
                int count = Math.Min(5, openItems.Count);
                for (int i = 0; i < count; i++)
                    sb.AppendLine($"- 🔲 {openItems[i].text}");
                sb.AppendLine();
            }
        }
        catch
        {
            sb.AppendLine("- (TODO verisi alinamadi)");
        }

        // --- Milestones ---
        sb.AppendLine("## Milestones");
        sb.AppendLine();
        try
        {
            var milestones = ProjectStateMilestone.ReadAll();
            if (milestones.Count == 0)
            {
                sb.AppendLine("- (Henuz milestone yok)");
            }
            else
            {
                int start = Math.Max(0, milestones.Count - 5);
                for (int i = milestones.Count - 1; i >= start; i--)
                {
                    var m      = milestones[i];
                    string ico = m.status == ProjectStateMilestone.MilestoneStatus.Done ? "✅" : "🔄";
                    sb.AppendLine($"- {ico} **{m.title}** ({m.date})");
                    if (!string.IsNullOrEmpty(m.note))
                        sb.AppendLine($"  - {m.note}");
                }
            }
        }
        catch
        {
            sb.AppendLine("- (Milestone verisi alinamadi)");
        }

        sb.AppendLine();
        sb.AppendLine(AutoBlockEnd);
        return sb.ToString();
    }

    // -----------------------------
    // HELPERS
    // -----------------------------

    private static string GetReadmePath()
    {
        string projectRoot = Directory.GetParent(Application.dataPath).FullName;
        return Path.Combine(projectRoot, "README.md");
    }

    private static string StripAutoBlock(string content)
    {
        int startIdx = content.IndexOf(AutoBlockStart, StringComparison.Ordinal);
        if (startIdx < 0) return content;
        return content.Substring(0, startIdx);
    }

    private static string BuildDefaultReadmeHeader()
    {
        return "# BladeRift\n\nMobile-first, first-person swipe combat game.\n\n";
    }

    private static string GetFolder(string path)
    {
        int idx = path.IndexOf("Scripts/", StringComparison.OrdinalIgnoreCase);
        if (idx < 0) return "Other";
        string after = path.Substring(idx + 8);
        int slash    = after.IndexOf('/');
        return slash >= 0 ? after.Substring(0, slash) : "Root";
    }

#endif
}
