using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;

#if UNITY_EDITOR
using UnityEditor;
#endif

// -----------------------------
// SCENE METRICS
// Triangle, light, renderer sayilarini toplar
// Snapshot meta'sına ek bilgi olarak eklenir
// -----------------------------

public static class ProjectStateSceneMetrics
{
    public class SceneMetricsData
    {
        public int rendererCount;
        public int lightCount;
        public int triangleCount;
        public int vertexCount;
        public int meshFilterCount;
        public int particleSystemCount;
        public int animatorCount;
        public int canvasCount;
    }

    // -----------------------------
    // COLLECT
    // -----------------------------

    public static SceneMetricsData Collect()
    {
        var data = new SceneMetricsData();

        // Renderers
        var renderers = Object.FindObjectsByType<Renderer>(FindObjectsSortMode.None);
        data.rendererCount = renderers.Length;

        // Lights
        data.lightCount = Object.FindObjectsByType<Light>(FindObjectsSortMode.None).Length;

        // Particle systems
        data.particleSystemCount = Object.FindObjectsByType<ParticleSystem>(FindObjectsSortMode.None).Length;

        // Animators
        data.animatorCount = Object.FindObjectsByType<Animator>(FindObjectsSortMode.None).Length;

        // Canvases
        data.canvasCount = Object.FindObjectsByType<Canvas>(FindObjectsSortMode.None).Length;

        // Triangle + vertex count (MeshFilter'lardan)
        var meshFilters = Object.FindObjectsByType<MeshFilter>(FindObjectsSortMode.None);
        data.meshFilterCount = meshFilters.Length;

        foreach (var mf in meshFilters)
        {
            if (mf == null || mf.sharedMesh == null) continue;
            data.triangleCount += mf.sharedMesh.triangles.Length / 3;
            data.vertexCount   += mf.sharedMesh.vertexCount;
        }

        return data;
    }

    // -----------------------------
    // SUMMARY — AUTOGENERATED icin
    // -----------------------------

    public static string BuildSummary()
    {
        var d = Collect();
        return
            $"- Renderers: {d.rendererCount}\n" +
            $"- Lights: {d.lightCount}\n" +
            $"- Triangles: {d.triangleCount:N0}\n" +
            $"- Vertices: {d.vertexCount:N0}\n" +
            $"- MeshFilters: {d.meshFilterCount}\n" +
            $"- ParticleSystems: {d.particleSystemCount}\n" +
            $"- Animators: {d.animatorCount}\n" +
            $"- Canvases: {d.canvasCount}";
    }

#if UNITY_EDITOR
    public static void PrintMetrics()
    {
        Debug.Log("[SceneMetrics]\n" + BuildSummary());
    }
#endif
}
