using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.SceneManagement;
#endif

// -----------------------------
// CHAT_STATE AUTOGENERATED WRITER
// Snapshot alindiginda otomatik cagirilir
// -----------------------------

public static class ProjectStateChatStateWriter
{
    private const string AutoBlockStart = "<!-- AUTOGENERATED - DO NOT EDIT BELOW THIS LINE -->";
    private const string AutoBlockEnd   = "<!-- END AUTOGENERATED -->";

#if UNITY_EDITOR

    public static void UpdateAutoBlock(FullSnapshot snapshot)
    {
        ProjectStateExporter.EnsureFolders();
        ProjectStateMilestone.EnsureMilestoneLogExists();

        string existing = File.Exists(ProjectStatePaths.ChatStatePath)
            ? File.ReadAllText(ProjectStatePaths.ChatStatePath, Encoding.UTF8)
            : "# CHAT_STATE\n";

        string manualPart = StripAutoBlock(existing);
        string autoBlock  = BuildAutoBlock(snapshot);
        string final      = manualPart.TrimEnd() + "\n\n" + autoBlock + "\n";

        File.WriteAllText(ProjectStatePaths.ChatStatePath, final, Encoding.UTF8);
    }

    private static string BuildAutoBlock(FullSnapshot snapshot)
    {
        var sb = new StringBuilder();

        sb.AppendLine(AutoBlockStart);
        sb.AppendLine();
        sb.AppendLine($"*Son guncelleme: {DateTime.Now:yyyy-MM-dd HH:mm:ss}*");
        sb.AppendLine();

        // --- Son Snapshot ---
        sb.AppendLine("## AUTO: Last Snapshot");
        if (snapshot != null)
        {
            sb.AppendLine($"- Kind: {snapshot.meta.snapshotKind}");
            sb.AppendLine($"- Date: {snapshot.meta.exportedAtLocalTime}");
            sb.AppendLine($"- Scene: {snapshot.meta.activeSceneName}");
            sb.AppendLine($"- Commit: {snapshot.meta.headCommitShort} — \"{snapshot.meta.headCommitMessage}\"");
            sb.AppendLine($"- Root objects: {snapshot.meta.rootObjectCount}");
            sb.AppendLine($"- Total objects: {snapshot.meta.totalGameObjectCount}");
        }
        else
        {
            string commitShort   = ProjectStateGit.SafeGit("rev-parse --short HEAD");
            string commitMessage = ProjectStateGit.SafeGit("log -1 --pretty=%s");
            sb.AppendLine($"- Commit: {commitShort} — \"{commitMessage}\"");
            sb.AppendLine("- (Snapshot verisi yok)");
        }

        // --- Script Dosyalari ---
        sb.AppendLine();
        sb.AppendLine("## AUTO: Script Files");
        if (snapshot?.code?.csFiles != null)
        {
            foreach (var f in snapshot.code.csFiles)
            {
                if (f.relativePath.Contains("TutorialInfo")) continue;
                if (f.relativePath.Contains("ProjectState"))  continue;
                sb.AppendLine($"- {f.relativePath}");
            }
        }
        else sb.AppendLine("- (Snapshot verisi yok)");

        // --- Sahne Hierarchy ---
        sb.AppendLine();
        sb.AppendLine("## AUTO: Scene Hierarchy (Summary)");
        if (snapshot?.scene?.roots != null)
        {
            foreach (var root in snapshot.scene.roots)
                WriteHierarchySummary(sb, root, 0);
        }
        else
        {
            var scene = EditorSceneManager.GetActiveScene();
            if (scene.IsValid())
            {
                foreach (var root in scene.GetRootGameObjects())
                {
                    var comps     = root.GetComponents<MonoBehaviour>();
                    var compNames = new List<string>();
                    foreach (var c in comps)
                        if (c != null) compNames.Add(c.GetType().Name);
                    string compStr = compNames.Count > 0 ? $" [{string.Join(", ", compNames)}]" : "";
                    sb.AppendLine($"- {root.name}{compStr}");
                }
            }
        }

        // --- Scene Metrics ---
        sb.AppendLine();
        sb.AppendLine("## AUTO: Scene Metrics");
        try   { sb.AppendLine(ProjectStateSceneMetrics.BuildSummary()); }
        catch { sb.AppendLine("- (Metrics alinamadi)"); }

        // --- Todo Summary ---
        sb.AppendLine();
        sb.AppendLine("## AUTO: Todo");
        try   { sb.Append(ProjectStateTodoSync.BuildSummary()); }
        catch { sb.AppendLine("- (TODO_TR.md okunamadi)"); }

        // --- Milestones ---
        sb.AppendLine();
        sb.AppendLine("## AUTO: Milestones");
        var milestones = ProjectStateMilestone.ReadAll();
        if (milestones.Count == 0)
        {
            sb.AppendLine("- (Henuz milestone yok)");
        }
        else
        {
            int start = Math.Max(0, milestones.Count - 10);
            for (int i = milestones.Count - 1; i >= start; i--)
            {
                var m         = milestones[i];
                string status = m.status == ProjectStateMilestone.MilestoneStatus.Done ? "DONE" : "REOPENED";
                sb.AppendLine($"- [{status}] {m.title} ({m.date})");
                if (!string.IsNullOrEmpty(m.note))
                    sb.AppendLine($"  - {m.note}");
                if (m.status == ProjectStateMilestone.MilestoneStatus.Reopened &&
                    !string.IsNullOrEmpty(m.previousCommit))
                    sb.AppendLine($"  - Onceki commit: {m.previousCommit}");
            }
        }

        sb.AppendLine();
        sb.AppendLine(AutoBlockEnd);

        return sb.ToString();
    }

    private static void WriteHierarchySummary(StringBuilder sb, GameObjectData obj, int depth)
    {
        if (depth > 2) return;

        string indent = new string(' ', depth * 2);
        string active = obj.activeSelf ? "" : " [inactive]";

        var compNames = new List<string>();
        if (obj.components != null)
        {
            foreach (var c in obj.components)
            {
                if (c?.type == null) continue;
                string shortName = ShortTypeName(c.type);
                if (shortName == "Transform" || shortName == "RectTransform") continue;
                compNames.Add(shortName);
            }
        }

        string compStr = compNames.Count > 0 ? $" [{string.Join(", ", compNames)}]" : "";
        sb.AppendLine($"{indent}- {obj.name}{active}{compStr}");

        if (obj.children != null)
            foreach (var child in obj.children)
                WriteHierarchySummary(sb, child, depth + 1);
    }

    private static string StripAutoBlock(string content)
    {
        int startIdx = content.IndexOf(AutoBlockStart, StringComparison.Ordinal);
        if (startIdx < 0) return content;
        return content.Substring(0, startIdx);
    }

    private static string ShortTypeName(string fullType)
    {
        if (string.IsNullOrEmpty(fullType)) return "?";
        int dot = fullType.LastIndexOf('.');
        return dot >= 0 ? fullType.Substring(dot + 1) : fullType;
    }

#endif
}
