using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
#endif

// -----------------------------
// MILESTONE LOG MANAGER
// -----------------------------

public static class ProjectStateMilestone
{
    // -----------------------------
    // MODELS
    // -----------------------------

    public enum MilestoneStatus { Done, Reopened }

    public class MilestoneEntry
    {
        public string title;
        public MilestoneStatus status;
        public string date;
        public string commitShort;
        public string note;          // sebep (özellikle reopen için)
        public string previousCommit; // reopen'da önceki commit
    }

    // -----------------------------
    // PATHS
    // -----------------------------

    private static string MilestonePath =>
        Path.Combine(ProjectStatePaths.StateRoot, "MILESTONE_LOG.md");

    // -----------------------------
    // PUBLIC API
    // -----------------------------

    public static void EnsureMilestoneLogExists()
    {
        Directory.CreateDirectory(ProjectStatePaths.StateRoot);
        if (!File.Exists(MilestonePath))
        {
            File.WriteAllText(MilestonePath,
@"# MILESTONE_LOG

> Bu dosya proje milestonelarini takip eder.
> Yonetim: Claude tarafindan yapilir. Manuel duzenleme yapma.

", Encoding.UTF8);
        }
    }

    public static void AddDone(string title, string note = "")
    {
        EnsureMilestoneLogExists();

        string commitShort = ProjectStateGit.SafeGit("rev-parse --short HEAD");
        string date        = DateTime.Now.ToString("yyyy-MM-dd HH:mm");

        var entry = new StringBuilder();
        entry.AppendLine();
        entry.AppendLine($"## [DONE] {title}");
        entry.AppendLine($"- Tamamlandi: {date}");
        entry.AppendLine($"- Commit: {commitShort}");
        if (!string.IsNullOrEmpty(note))
            entry.AppendLine($"- Not: {note}");

        File.AppendAllText(MilestonePath, entry.ToString(), Encoding.UTF8);

        Debug.Log($"[Milestone] DONE: {title}");
    }

    public static void AddReopened(string title, string reason, string previousCommit = "")
    {
        EnsureMilestoneLogExists();

        string commitShort = ProjectStateGit.SafeGit("rev-parse --short HEAD");
        string date        = DateTime.Now.ToString("yyyy-MM-dd HH:mm");

        var entry = new StringBuilder();
        entry.AppendLine();
        entry.AppendLine($"## [REOPENED] {title}");
        entry.AppendLine($"- Yeniden acildi: {date}");
        entry.AppendLine($"- Commit: {commitShort}");
        entry.AppendLine($"- Sebep: {reason}");
        if (!string.IsNullOrEmpty(previousCommit))
            entry.AppendLine($"- Onceki commit: {previousCommit}");

        File.AppendAllText(MilestonePath, entry.ToString(), Encoding.UTF8);

        Debug.Log($"[Milestone] REOPENED: {title} — {reason}");
    }

    // -----------------------------
    // READ — AUTOGENERATED blok icin
    // -----------------------------

    public static List<MilestoneEntry> ReadAll()
    {
        var result = new List<MilestoneEntry>();

        if (!File.Exists(MilestonePath))
            return result;

        string[] lines = File.ReadAllLines(MilestonePath, Encoding.UTF8);
        MilestoneEntry current = null;

        foreach (var rawLine in lines)
        {
            string line = rawLine.Trim();

            if (line.StartsWith("## [DONE]"))
            {
                current = new MilestoneEntry
                {
                    status = MilestoneStatus.Done,
                    title  = line.Replace("## [DONE]", "").Trim()
                };
                result.Add(current);
            }
            else if (line.StartsWith("## [REOPENED]"))
            {
                current = new MilestoneEntry
                {
                    status = MilestoneStatus.Reopened,
                    title  = line.Replace("## [REOPENED]", "").Trim()
                };
                result.Add(current);
            }
            else if (current != null)
            {
                if (line.StartsWith("- Tamamlandi:") || line.StartsWith("- Yeniden acildi:"))
                    current.date = line.Substring(line.IndexOf(':') + 1).Trim();
                else if (line.StartsWith("- Commit:"))
                    current.commitShort = line.Replace("- Commit:", "").Trim();
                else if (line.StartsWith("- Not:"))
                    current.note = line.Replace("- Not:", "").Trim();
                else if (line.StartsWith("- Sebep:"))
                    current.note = line.Replace("- Sebep:", "").Trim();
                else if (line.StartsWith("- Onceki commit:"))
                    current.previousCommit = line.Replace("- Onceki commit:", "").Trim();
            }
        }

        return result;
    }

#if UNITY_EDITOR
    // -----------------------------
    // MENU
    // -----------------------------

    public static void OpenMilestoneLog()
    {
        EnsureMilestoneLogExists();
        EditorUtility.RevealInFinder(MilestonePath);
    }
#endif
}
