using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
#endif

// -----------------------------
// TODO SYNC
// Reads TODO_TR.md and parses [ ] / [x] items
// -----------------------------

public static class ProjectStateTodoSync
{
    public class TodoItem
    {
        public string text;
        public bool done;
        public string section; // hangi başlık altında
    }

    // -----------------------------
    // TODO_TR.md path
    // -----------------------------

    private static string TodoPath =>
        Path.Combine(ProjectStatePaths.DocsRoot, "..", "..", "Docs", "State", "TODO_TR.md")
            .Replace("State", "")
            .Replace("//", "/");

    // Doğrudan _Project/Docs altında değil, repo kökündeyse şu path:
    // Assets/_Project/Docs/... değil, kullanıcı TODO_TR.md'yi nereye koydu?
    // CHAT_STATE ile aynı klasörde: Assets/_Project/Docs/State/ altında değil
    // Repoya bakınca: Assets/_Project/Docs/Design/ veya State/ altında
    // ChatState'e göre: ARCHITECTURE_TR, GAME_CONCEPT_TR, GAME_RULES_TR = Design klasöründe
    // TODO_TR = State klasöründe mi? Emin değilim, her iki yeri de dene

    private static string[] PossibleTodoPaths => new[]
    {
        Path.Combine(ProjectStatePaths.StateRoot, "TODO_TR.md"),
        Path.Combine(ProjectStatePaths.DocsRoot, "TODO_TR.md"),
        Path.Combine(ProjectStatePaths.DocsRoot, "Design", "TODO_TR.md"),
        // Repo root seviyesinde de olabilir
        Path.Combine(Directory.GetParent(Application.dataPath).FullName, "TODO_TR.md"),
    };

    // -----------------------------
    // READ
    // -----------------------------

    public static List<TodoItem> ReadAll()
    {
        string path = FindTodoPath();
        var result  = new List<TodoItem>();

        if (string.IsNullOrEmpty(path)) return result;

        string[] lines   = File.ReadAllLines(path, Encoding.UTF8);
        string curSection = "";

        foreach (var raw in lines)
        {
            string line = raw.Trim();

            // Başlık tespiti
            if (line.StartsWith("#"))
            {
                curSection = line.TrimStart('#').Trim();
                continue;
            }

            // Done item
            if (line.StartsWith("- [x]") || line.StartsWith("- [X]"))
            {
                result.Add(new TodoItem
                {
                    done    = true,
                    text    = line.Substring(5).Trim(),
                    section = curSection
                });
            }
            // Open item
            else if (line.StartsWith("- [ ]"))
            {
                result.Add(new TodoItem
                {
                    done    = false,
                    text    = line.Substring(5).Trim(),
                    section = curSection
                });
            }
        }

        return result;
    }

    public static string FindTodoPath()
    {
        foreach (var p in PossibleTodoPaths)
            if (File.Exists(p)) return p;
        return null;
    }

    // -----------------------------
    // SUMMARY — AUTOGENERATED icin
    // Sadece open itemleri + son 5 done'i goster
    // -----------------------------

    public static string BuildSummary()
    {
        var all  = ReadAll();
        var sb   = new StringBuilder();

        if (all.Count == 0)
        {
            sb.AppendLine("- (TODO_TR.md bulunamadi veya bos)");
            return sb.ToString();
        }

        var open = new List<TodoItem>();
        var done = new List<TodoItem>();

        foreach (var item in all)
            if (item.done) done.Add(item);
            else            open.Add(item);

        sb.AppendLine($"Open: {open.Count} | Done: {done.Count}");
        sb.AppendLine();

        // Open itemleri section bazli goster (max 15)
        string lastSection = "";
        int shown = 0;
        foreach (var item in open)
        {
            if (shown >= 15) { sb.AppendLine("  ... (daha fazlasi var)"); break; }
            if (item.section != lastSection)
            {
                sb.AppendLine($"  **{item.section}**");
                lastSection = item.section;
            }
            sb.AppendLine($"  - [ ] {item.text}");
            shown++;
        }

        // Son 5 done
        if (done.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("  Son tamamlananlar:");
            int start = System.Math.Max(0, done.Count - 5);
            for (int i = done.Count - 1; i >= start; i--)
                sb.AppendLine($"  - [x] {done[i].text}");
        }

        return sb.ToString();
    }

#if UNITY_EDITOR
    public static void PrintTodoSummary()
    {
        string path = FindTodoPath();
        Debug.Log($"[TodoSync] TODO path: {path ?? "NOT FOUND"}");
        Debug.Log("[TodoSync] Summary:\n" + BuildSummary());
    }
#endif
}
